# Generated by Django 5.2.5 on 2025-09-03 12:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupdiscussion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gdparticipant',
            unique_together={('session', 'student')},
        ),
    ]
